server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: USER-SERVICE
          uri: lb://user-service/
          predicates:
            - Path=/user/**
        - id: car-service
          uri: lb://car-service/
          predicates:
            - Path=/api/car/**
        - id: moto-service
          uri: lb://moto-service/
          predicates:
            - Path=/moto/**

